jobs:
  include:
    - stage: quarkus-backend
      language: java
      jdk: 
        - oraclejdk11
      branches:
        only:
          - master
      cache:
        directories:
          - $HOME/.m2
          - $HOME/.gradle
      before_script: 
        - cd quarkus-backend
      script: 
        - ./gradlew clean build  

    - stage: vuejs-frontend
      language: node_js
      node_js:
        - "12.0"
      branches:
        only:
          - master
      cache:
        directories:
          - ./node_modules
      before_script:
        - cd vuejs-frontend
        - npm install
      script:
        - npm run lint
        - npm run test:unit
          