quarkus:
  datasource:
    db-kind: h2
    username: sa
    password: password
    jdbc:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    cors: true

